# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SC Docker tests pipeline

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  basic:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['4.6.2', '4.6.2-alpine-glibc']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Start Sauce Connect
        run: |
          docker run -e SAUCE_USERNAME=${SAUCE_USERNAME} -e SAUCE_ACCESS_KEY=${SAUCE_ACCESS_KEY} -it saucelabs/sauce-connect:${{ matrix.tag }}

      - name: Upload generated Dockerfiles
        uses: actions/upload-artifact@v2
        with:
          name: dockerfiles
          path: dist/